org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8
kotlin.daemon.jvm.options=-Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process
googleServices.missing.passthrough=true
android.builtInKotlin=false
android.newDsl=false
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.gradle.vfs.watch=false
org.gradle.daemon=false
org.gradle.configuration-cache=false